name: Build & deploy to staging
on:
  pull_request:
    branches: [staging]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS App
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            mkdir staging
            cd staging
            git clone git@github.com:Grade-Arc/Grade-Arc-Api-v2.git
            echo 'Deployment successful to digital ocean'
